name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: UDS CLI Setup
        uses: defenseunicorns-udm/udm-common/.github/actions/uds-cli-setup@313297d92b3b10e1d86b18c5861a3099b46b7377 # v0.6.0

      # Lint logic is owned by the calling repo via a UDS task.
      # Define a 'lint' task in your tasks.yaml that runs your linter(s).
      - name: Witness Run Lint
        uses: defenseunicorns-udm/udm-common/.github/actions/witness-run@313297d92b3b10e1d86b18c5861a3099b46b7377 # v0.6.0
        with:
          step: lint
          command: uds run lint
          outfile: lint-witness.json

      - name: Upload lint artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lint-artifacts
          path: lint-witness.json

  scan-vouch-publish:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: UDS CLI Setup
        uses: defenseunicorns-udm/udm-common/.github/actions/uds-cli-setup@313297d92b3b10e1d86b18c5861a3099b46b7377 # v0.6.0

      - name: Download lint artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: lint-artifacts
          path: .

      - name: Security Scan
        run: |
          uds run scan:security

      - name: Vouch
        run: |
          uds run vouch:package \
            --with github_token="${{ secrets.GITHUB_TOKEN }}" \
            --with attestations="gitleaks-witness.json,opengrep-witness.json,lint-witness.json" \
            --with sarif_files="gitleaks.sarif.json,opengrep.sarif.json" \
            --with olm_cat=cat-api.uds-mil.us \
            --with olm_org="<your-org-name>"

      - name: Publish
        run: |
          uds run publish:zarf-package \
            --with registry_org="<your-org-name>" \
            --with registry_user_id="${{ secrets.REGISTRY_USER_ID }}" \
            --with registry_password="${{ secrets.REGISTRY_PASSWORD }}"
