name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Run task integration tests
        run: uds run test

  scan-vouch-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Generate Fulcio Token
        run: |
          uds run olm:generate-fulcio-token \
            --with olm_cat="cat-api.uds-mil.us" \
            --with olm_org="${{ secrets.OLM_ORG }}" \
            --with github_token="${{ secrets.GITHUB_TOKEN }}"

      - name: Witness Run Lint
        run: uds run attest:lint

      - name: Security Scan
        run: |
          uds run scan:security \
            --with opengrep_scan_path=src/ \
            --with gitleaks_scan_path=src/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Refresh Fulcio Token
        run: |
          uds run olm:generate-fulcio-token \
            --with olm_cat="cat-api.uds-mil.us" \
            --with olm_org="${{ secrets.OLM_ORG }}" \
            --with github_token="${{ secrets.GITHUB_TOKEN }}"

      - name: Build Zarf Package
        run: uds run build:zarf-package

      - name: Vouch Zarf Package via OLM
        run: |
          uds run vouch:package \
            --with olm_cat="cat-api.uds-mil.us" \
            --with olm_org="${{ secrets.OLM_ORG }}" \
            --with attestations="lint-witness.json,gitleaks-witness.json,opengrep-witness.json,zarf-create-witness.json" \
            --with sarif_files="gitleaks.sarif.json,opengrep.sarif.json"

      - name: Publish Zarf Package to Registry
        run: |
          uds run publish:zarf-package \
            --with registry_org="${{ secrets.REGISTRY_ORG }}" \
            --with registry_user_id="${{ secrets.REGISTRY_USER_ID }}" \
            --with registry_password="${{ secrets.REGISTRY_PASSWORD }}"
