name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Run task integration tests
        run: uds run test --no-progress

  scan-vouch-publish:
    uses: ./.github/workflows/scan-vouch-publish.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets:
      OLM_ORG: ${{ secrets.OLM_ORG }}
      REGISTRY_ORG: ${{ secrets.REGISTRY_ORG }}
      REGISTRY_USER_ID: ${{ secrets.REGISTRY_USER_ID }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
